# Generated by Django 5.1 on 2024-08-15 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrichedcompany',
            name='enriched_data',
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='foundedOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='logoResolutionResult',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='specialities',
            field=models.TextField(blank=True, max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='tagline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='universalName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='websiteUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_linkedin_url',
            field=models.URLField(unique=True),
        ),
    ]
