# Generated by Django 5.1 on 2024-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0002_remove_enrichedcompany_enriched_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichedcompany',
            name='headquarter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
