# Generated by Django 5.1 on 2024-08-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0003_enrichedcompany_headquarter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='url',
            new_name='linkedinUrl',
        ),
    ]
