# Generated by Django 5.1 on 2024-08-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0004_rename_url_enrichedcompany_linkedinurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='company',
            new_name='companyId',
        ),
        migrations.AddField(
            model_name='enrichedcompany',
            name='companyName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
