# Generated by Django 5.1 on 2024-08-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0005_rename_company_enrichedcompany_companyid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='companyId',
            new_name='company',
        ),
    ]
