# Generated by Django 5.1 on 2024-08-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0006_rename_companyid_enrichedcompany_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='company',
            new_name='companyId',
        ),
    ]
