# Generated by Django 5.1 on 2024-08-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_data', '0007_rename_company_enrichedcompany_companyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='companyId',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='foundedOn',
            new_name='founded_on',
        ),
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='linkedinUrl',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='logoResolutionResult',
            new_name='logo_resolution_result',
        ),
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='universalName',
            new_name='universal_name',
        ),
        migrations.RenameField(
            model_name='enrichedcompany',
            old_name='websiteUrl',
            new_name='website_url',
        ),
    ]
